services:
  # Serviço do Banco de Dados
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234  # Mudei para 'password' para bater com seu Java
      POSTGRES_DB: feirinha_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # A LINHA MÁGICA ESTAVA FALTANDO AQUI EMBAIXO:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Serviço da sua Aplicação Java
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_NAME: feirinha_db
      DB_USER: postgres
      DB_PASS: 1234

volumes:
  postgres_data: